# Generated by Django 3.2.19 on 2023-06-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_deal_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('الکترونیک و تکنولوژی', 'ELECT'), ('ماشین', 'CAR'), ('خرید پیشنهادها', 'BID'), ('وسایل خانه و باغبانی', 'HOME'), ('آرایشی بهداشتی', 'COSMETIC'), ('پوشاک و فشن', 'FASHION'), ('کارت هدیه', 'CARD'), ('آشپزخانه و غذاخوری', 'KITCHEN'), ('باقی', 'OTHER')], max_length=50),
        ),
    ]
