# Generated by Django 3.2.19 on 2023-05-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20230512_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bids',
            field=models.IntegerField(default=0),
        ),
    ]
