# Generated by Django 3.2.19 on 2023-05-13 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
