# Generated by Django 3.2.19 on 2023-06-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230613_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('الکترونیک و تکنولوژی', 'ELECT'), ('ماشین', 'CAR'), ('توکن پیشنهادها', 'BID'), ('وسایل خانه و باغبانی', 'HOME'), ('آرایشی بهداشتی', 'COSMETIC'), ('پوشاک و فشن', 'FASHION'), ('کارت هدیه', 'CARD'), ('آشپزخانه و غذاخوری', 'KITCHEN'), ('خوراکی و سوپرمارکت', 'FOOD'), ('باقی', 'OTHER')], max_length=50),
        ),
    ]
