# Generated by Django 3.2.19 on 2023-05-14 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20230514_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='product',
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.auction'),
        ),
    ]
