# Generated by Django 3.2.19 on 2023-05-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_transaction_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-date_modified']},
        ),
        migrations.AddField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
