# Generated by Django 3.2.19 on 2023-05-16 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20230516_0737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='auction',
            name='last_bidder',
        ),
        migrations.AddField(
            model_name='auction',
            name='last_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_last_bid', to='base.bid'),
        ),
    ]
