# Generated by Django 3.2.19 on 2023-05-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20230516_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='time',
        ),
    ]
