# Generated by Django 3.2.19 on 2023-05-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20230527_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, null=True, to='base.Product'),
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
