# Generated by Django 3.2.19 on 2023-05-27 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20230527_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='discount',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal', to='base.discount'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, to='base.Product'),
        ),
    ]
